package flixel.input.keyboard;

#if CODENAME_ENGINE_COMPAT
/**
 * Runtime reflection surface for the FlxKey enum abstract used by HScript.
 *
 * Enum abstracts are erased by Haxe and cannot be found through
 * `Type.resolveClass()`.  HScript automatically retries imports with the
 * `_HSC` suffix, so keep this as a regular class with getter-backed fields.
 */
class FlxKey_HSC
{
	public static var fromStringMap(get, never):Map<String, FlxKey>;
	public static var toStringMap(get, never):Map<FlxKey, String>;

	public static var ANY(get, never):FlxKey;
	public static var NONE(get, never):FlxKey;
	public static var A(get, never):FlxKey;
	public static var B(get, never):FlxKey;
	public static var C(get, never):FlxKey;
	public static var D(get, never):FlxKey;
	public static var E(get, never):FlxKey;
	public static var F(get, never):FlxKey;
	public static var G(get, never):FlxKey;
	public static var H(get, never):FlxKey;
	public static var I(get, never):FlxKey;
	public static var J(get, never):FlxKey;
	public static var K(get, never):FlxKey;
	public static var L(get, never):FlxKey;
	public static var M(get, never):FlxKey;
	public static var N(get, never):FlxKey;
	public static var O(get, never):FlxKey;
	public static var P(get, never):FlxKey;
	public static var Q(get, never):FlxKey;
	public static var R(get, never):FlxKey;
	public static var S(get, never):FlxKey;
	public static var T(get, never):FlxKey;
	public static var U(get, never):FlxKey;
	public static var V(get, never):FlxKey;
	public static var W(get, never):FlxKey;
	public static var X(get, never):FlxKey;
	public static var Y(get, never):FlxKey;
	public static var Z(get, never):FlxKey;
	public static var ZERO(get, never):FlxKey;
	public static var ONE(get, never):FlxKey;
	public static var TWO(get, never):FlxKey;
	public static var THREE(get, never):FlxKey;
	public static var FOUR(get, never):FlxKey;
	public static var FIVE(get, never):FlxKey;
	public static var SIX(get, never):FlxKey;
	public static var SEVEN(get, never):FlxKey;
	public static var EIGHT(get, never):FlxKey;
	public static var NINE(get, never):FlxKey;
	public static var PAGEUP(get, never):FlxKey;
	public static var PAGEDOWN(get, never):FlxKey;
	public static var HOME(get, never):FlxKey;
	public static var END(get, never):FlxKey;
	public static var INSERT(get, never):FlxKey;
	public static var ESCAPE(get, never):FlxKey;
	public static var MINUS(get, never):FlxKey;
	public static var PLUS(get, never):FlxKey;
	public static var DELETE(get, never):FlxKey;
	public static var BACKSPACE(get, never):FlxKey;
	public static var LBRACKET(get, never):FlxKey;
	public static var RBRACKET(get, never):FlxKey;
	public static var BACKSLASH(get, never):FlxKey;
	public static var CAPSLOCK(get, never):FlxKey;
	public static var SCROLL_LOCK(get, never):FlxKey;
	public static var NUMLOCK(get, never):FlxKey;
	public static var SEMICOLON(get, never):FlxKey;
	public static var QUOTE(get, never):FlxKey;
	public static var ENTER(get, never):FlxKey;
	public static var SHIFT(get, never):FlxKey;
	public static var COMMA(get, never):FlxKey;
	public static var PERIOD(get, never):FlxKey;
	public static var SLASH(get, never):FlxKey;
	public static var GRAVEACCENT(get, never):FlxKey;
	public static var CONTROL(get, never):FlxKey;
	public static var ALT(get, never):FlxKey;
	public static var SPACE(get, never):FlxKey;
	public static var UP(get, never):FlxKey;
	public static var DOWN(get, never):FlxKey;
	public static var LEFT(get, never):FlxKey;
	public static var RIGHT(get, never):FlxKey;
	public static var TAB(get, never):FlxKey;
	public static var WINDOWS(get, never):FlxKey;
	public static var MENU(get, never):FlxKey;
	public static var PRINTSCREEN(get, never):FlxKey;
	public static var BREAK(get, never):FlxKey;
	public static var F1(get, never):FlxKey;
	public static var F2(get, never):FlxKey;
	public static var F3(get, never):FlxKey;
	public static var F4(get, never):FlxKey;
	public static var F5(get, never):FlxKey;
	public static var F6(get, never):FlxKey;
	public static var F7(get, never):FlxKey;
	public static var F8(get, never):FlxKey;
	public static var F9(get, never):FlxKey;
	public static var F10(get, never):FlxKey;
	public static var F11(get, never):FlxKey;
	public static var F12(get, never):FlxKey;
	public static var NUMPADZERO(get, never):FlxKey;
	public static var NUMPADONE(get, never):FlxKey;
	public static var NUMPADTWO(get, never):FlxKey;
	public static var NUMPADTHREE(get, never):FlxKey;
	public static var NUMPADFOUR(get, never):FlxKey;
	public static var NUMPADFIVE(get, never):FlxKey;
	public static var NUMPADSIX(get, never):FlxKey;
	public static var NUMPADSEVEN(get, never):FlxKey;
	public static var NUMPADEIGHT(get, never):FlxKey;
	public static var NUMPADNINE(get, never):FlxKey;
	public static var NUMPADMINUS(get, never):FlxKey;
	public static var NUMPADPLUS(get, never):FlxKey;
	public static var NUMPADPERIOD(get, never):FlxKey;
	public static var NUMPADMULTIPLY(get, never):FlxKey;
	public static var NUMPADSLASH(get, never):FlxKey;

	private static inline function get_fromStringMap():Map<String, FlxKey> return FlxKey.fromStringMap;
	private static inline function get_toStringMap():Map<FlxKey, String> return FlxKey.toStringMap;

	private static inline function get_ANY():FlxKey return FlxKey.ANY;
	private static inline function get_NONE():FlxKey return FlxKey.NONE;
	private static inline function get_A():FlxKey return FlxKey.A;
	private static inline function get_B():FlxKey return FlxKey.B;
	private static inline function get_C():FlxKey return FlxKey.C;
	private static inline function get_D():FlxKey return FlxKey.D;
	private static inline function get_E():FlxKey return FlxKey.E;
	private static inline function get_F():FlxKey return FlxKey.F;
	private static inline function get_G():FlxKey return FlxKey.G;
	private static inline function get_H():FlxKey return FlxKey.H;
	private static inline function get_I():FlxKey return FlxKey.I;
	private static inline function get_J():FlxKey return FlxKey.J;
	private static inline function get_K():FlxKey return FlxKey.K;
	private static inline function get_L():FlxKey return FlxKey.L;
	private static inline function get_M():FlxKey return FlxKey.M;
	private static inline function get_N():FlxKey return FlxKey.N;
	private static inline function get_O():FlxKey return FlxKey.O;
	private static inline function get_P():FlxKey return FlxKey.P;
	private static inline function get_Q():FlxKey return FlxKey.Q;
	private static inline function get_R():FlxKey return FlxKey.R;
	private static inline function get_S():FlxKey return FlxKey.S;
	private static inline function get_T():FlxKey return FlxKey.T;
	private static inline function get_U():FlxKey return FlxKey.U;
	private static inline function get_V():FlxKey return FlxKey.V;
	private static inline function get_W():FlxKey return FlxKey.W;
	private static inline function get_X():FlxKey return FlxKey.X;
	private static inline function get_Y():FlxKey return FlxKey.Y;
	private static inline function get_Z():FlxKey return FlxKey.Z;
	private static inline function get_ZERO():FlxKey return FlxKey.ZERO;
	private static inline function get_ONE():FlxKey return FlxKey.ONE;
	private static inline function get_TWO():FlxKey return FlxKey.TWO;
	private static inline function get_THREE():FlxKey return FlxKey.THREE;
	private static inline function get_FOUR():FlxKey return FlxKey.FOUR;
	private static inline function get_FIVE():FlxKey return FlxKey.FIVE;
	private static inline function get_SIX():FlxKey return FlxKey.SIX;
	private static inline function get_SEVEN():FlxKey return FlxKey.SEVEN;
	private static inline function get_EIGHT():FlxKey return FlxKey.EIGHT;
	private static inline function get_NINE():FlxKey return FlxKey.NINE;
	private static inline function get_PAGEUP():FlxKey return FlxKey.PAGEUP;
	private static inline function get_PAGEDOWN():FlxKey return FlxKey.PAGEDOWN;
	private static inline function get_HOME():FlxKey return FlxKey.HOME;
	private static inline function get_END():FlxKey return FlxKey.END;
	private static inline function get_INSERT():FlxKey return FlxKey.INSERT;
	private static inline function get_ESCAPE():FlxKey return FlxKey.ESCAPE;
	private static inline function get_MINUS():FlxKey return FlxKey.MINUS;
	private static inline function get_PLUS():FlxKey return FlxKey.PLUS;
	private static inline function get_DELETE():FlxKey return FlxKey.DELETE;
	private static inline function get_BACKSPACE():FlxKey return FlxKey.BACKSPACE;
	private static inline function get_LBRACKET():FlxKey return FlxKey.LBRACKET;
	private static inline function get_RBRACKET():FlxKey return FlxKey.RBRACKET;
	private static inline function get_BACKSLASH():FlxKey return FlxKey.BACKSLASH;
	private static inline function get_CAPSLOCK():FlxKey return FlxKey.CAPSLOCK;
	private static inline function get_SCROLL_LOCK():FlxKey return FlxKey.SCROLL_LOCK;
	private static inline function get_NUMLOCK():FlxKey return FlxKey.NUMLOCK;
	private static inline function get_SEMICOLON():FlxKey return FlxKey.SEMICOLON;
	private static inline function get_QUOTE():FlxKey return FlxKey.QUOTE;
	private static inline function get_ENTER():FlxKey return FlxKey.ENTER;
	private static inline function get_SHIFT():FlxKey return FlxKey.SHIFT;
	private static inline function get_COMMA():FlxKey return FlxKey.COMMA;
	private static inline function get_PERIOD():FlxKey return FlxKey.PERIOD;
	private static inline function get_SLASH():FlxKey return FlxKey.SLASH;
	private static inline function get_GRAVEACCENT():FlxKey return FlxKey.GRAVEACCENT;
	private static inline function get_CONTROL():FlxKey return FlxKey.CONTROL;
	private static inline function get_ALT():FlxKey return FlxKey.ALT;
	private static inline function get_SPACE():FlxKey return FlxKey.SPACE;
	private static inline function get_UP():FlxKey return FlxKey.UP;
	private static inline function get_DOWN():FlxKey return FlxKey.DOWN;
	private static inline function get_LEFT():FlxKey return FlxKey.LEFT;
	private static inline function get_RIGHT():FlxKey return FlxKey.RIGHT;
	private static inline function get_TAB():FlxKey return FlxKey.TAB;
	private static inline function get_WINDOWS():FlxKey return FlxKey.WINDOWS;
	private static inline function get_MENU():FlxKey return FlxKey.MENU;
	private static inline function get_PRINTSCREEN():FlxKey return FlxKey.PRINTSCREEN;
	private static inline function get_BREAK():FlxKey return FlxKey.BREAK;
	private static inline function get_F1():FlxKey return FlxKey.F1;
	private static inline function get_F2():FlxKey return FlxKey.F2;
	private static inline function get_F3():FlxKey return FlxKey.F3;
	private static inline function get_F4():FlxKey return FlxKey.F4;
	private static inline function get_F5():FlxKey return FlxKey.F5;
	private static inline function get_F6():FlxKey return FlxKey.F6;
	private static inline function get_F7():FlxKey return FlxKey.F7;
	private static inline function get_F8():FlxKey return FlxKey.F8;
	private static inline function get_F9():FlxKey return FlxKey.F9;
	private static inline function get_F10():FlxKey return FlxKey.F10;
	private static inline function get_F11():FlxKey return FlxKey.F11;
	private static inline function get_F12():FlxKey return FlxKey.F12;
	private static inline function get_NUMPADZERO():FlxKey return FlxKey.NUMPADZERO;
	private static inline function get_NUMPADONE():FlxKey return FlxKey.NUMPADONE;
	private static inline function get_NUMPADTWO():FlxKey return FlxKey.NUMPADTWO;
	private static inline function get_NUMPADTHREE():FlxKey return FlxKey.NUMPADTHREE;
	private static inline function get_NUMPADFOUR():FlxKey return FlxKey.NUMPADFOUR;
	private static inline function get_NUMPADFIVE():FlxKey return FlxKey.NUMPADFIVE;
	private static inline function get_NUMPADSIX():FlxKey return FlxKey.NUMPADSIX;
	private static inline function get_NUMPADSEVEN():FlxKey return FlxKey.NUMPADSEVEN;
	private static inline function get_NUMPADEIGHT():FlxKey return FlxKey.NUMPADEIGHT;
	private static inline function get_NUMPADNINE():FlxKey return FlxKey.NUMPADNINE;
	private static inline function get_NUMPADMINUS():FlxKey return FlxKey.NUMPADMINUS;
	private static inline function get_NUMPADPLUS():FlxKey return FlxKey.NUMPADPLUS;
	private static inline function get_NUMPADPERIOD():FlxKey return FlxKey.NUMPADPERIOD;
	private static inline function get_NUMPADMULTIPLY():FlxKey return FlxKey.NUMPADMULTIPLY;
	private static inline function get_NUMPADSLASH():FlxKey return FlxKey.NUMPADSLASH;

	public static inline function fromString(value:String):FlxKey
		return FlxKey.fromString(value);
}
#end
